// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAje6xIaDVPh3zG0huH2yR01O51H888fe4',
    appId: '1:185692241713:web:15e2b24f0c38dca4367a10',
    messagingSenderId: '185692241713',
    projectId: 'fruit-hub-ca01d',
    authDomain: 'fruit-hub-ca01d.firebaseapp.com',
    storageBucket: 'fruit-hub-ca01d.firebasestorage.app',
    measurementId: 'G-2MR1CS2N62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTnHeIPFmGsKAkFhI6dudAXPR61Tlgc3E',
    appId: '1:185692241713:android:2c793a06fc228c9f367a10',
    messagingSenderId: '185692241713',
    projectId: 'fruit-hub-ca01d',
    storageBucket: 'fruit-hub-ca01d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB54PkVk1rFYevSImnWDJKl6Af8EoVLbM0',
    appId: '1:185692241713:ios:d67f4fb4b3fa2a25367a10',
    messagingSenderId: '185692241713',
    projectId: 'fruit-hub-ca01d',
    storageBucket: 'fruit-hub-ca01d.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB54PkVk1rFYevSImnWDJKl6Af8EoVLbM0',
    appId: '1:185692241713:ios:d67f4fb4b3fa2a25367a10',
    messagingSenderId: '185692241713',
    projectId: 'fruit-hub-ca01d',
    storageBucket: 'fruit-hub-ca01d.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAje6xIaDVPh3zG0huH2yR01O51H888fe4',
    appId: '1:185692241713:web:ecf2c5aa39bb3fd9367a10',
    messagingSenderId: '185692241713',
    projectId: 'fruit-hub-ca01d',
    authDomain: 'fruit-hub-ca01d.firebaseapp.com',
    storageBucket: 'fruit-hub-ca01d.firebasestorage.app',
    measurementId: 'G-Y7MHX1SJ7G',
  );
}
